### ISSUE TITLE
UX: the domain is contradictory with the first header

### ISSUE THREAD

**Issue by SebCorbin** [rosslh/IsEarthStillWarming.com#12]
domain: isearthstillwarming.com
first header: Have we stopped global warming yet?

One of the first thing the user see is the red stamp "NO" when the eye analyze the page so it would be better to have the first header with the same sense as the domain, like "Is global warming still happening?" or something like that and modify NO with YES but keeping the red color

**Comment by rosslh** [comment]
Good point, I'll change that
