### ISSUE TITLE
feature: countdown

### ISSUE THREAD

**Issue by EmanuelGF** [rosslh/IsEarthStillWarming.com#125]
Just an idea... (¬‿¬)
How about having a countdown from the Paris agreement date you have posted on the website?
I think this would create a bigger impact on site users.
Check out the example: [codepen](https://codepen.io/emanuelgf/pen/mdJmydE)

**Comment by rosslh** [comment]
Neat idea but I don't think we'll implement this. It's really just a rough estimate, so showing a countdown with such high precision (days, hours, minutes...) doesn't make much sense in my opinion.
