### ISSUE TITLE
Expand 'effects of global warming' section

### ISSUE THREAD

**Issue by rosslh** [rosslh/IsEarthStillWarming.com#15]

**Comment by bkstephen** [comment]
Hey, I'd like to help with this project. What additions for the  'effects of global warming' section do you have in mind?

**Comment by shakti97** [comment]
is this issue still incomplete or done but not marked closed?

**Comment by AnkitaBIT** [comment]
@rosslh ,is this issue still available?

**Comment by rosslh** [comment]
Hi all, sorry for the late reply. This issue is still open for contributors, so feel free to [make a pull request](https://help.github.com/en/articles/creating-a-pull-request) with some added content. Right now we include details on:

- Which regions are likely to be affected the most
- Weather extremes
- Temperature extremes
- Dying coral reefs
- Ice melt / sea level rise
- Drought / food and water shortages

You may expand our information on any of those effects of global warming, or you can add information that is missing entirely. [This Wikipedia article](https://en.wikipedia.org/wiki/Effects_of_global_warming) is a good place to look for some ideas (global warming's effect on migration and conflict for example).

Each piece of information you add should be cited to a reliable source (e.g. a newspaper, a peer reviewed journal, or a government agency).

The content of the website is located at `src/pages/index.js`. You should put new citations in `src/components/reflist.js`. The instructions to build the project are in [the ReadMe](https://github.com/rosslh/IsEarthStillWarming.com/blob/master/README.md).

Please let me know if you have any questions!

**Comment by MindFluid** [comment]
I hope I have done this correctly -- I know this piece of information was fairly moving when I learned of it.
