### ISSUE TITLE
Rate of sea level rise displayed in header is wrong (or badly presented)

### ISSUE THREAD

**Issue by willbeaufoy** [rosslh/IsEarthStillWarming.com#202]
Right now the rate of sea level rise displayed in the header is 63mm/year, which is way off ([NASA](https://climate.nasa.gov/) has it at 3.3mm/year). Is this bad data or bad presentation? I'd be happy to fix this if needed.

**Comment by rosslh** [comment]
Thanks for pointing this out! Closed in 69922b334a9c3a9c222621999682d51f598f5f30.
