### ISSUE TITLE
Cite/reflist enhancements

### ISSUE THREAD

**Issue by rosslh** [rosslh/IsEarthStillWarming.com#6]
- [x] smooth scroll
- [x] highlight reflist item
- [ ] tooltip on hover?

**Comment by eostrom** [comment]
Hi! Would you be open to a PR for this? I added smooth scroll to https://climatechoice.co (also a React app, by way of Gatsby), and I'd like to try adding that and the other two things here as well.

**Comment by rosslh** [comment]
Hi @eostrom, yes a PR for this would be appreciated!

**Comment by eostrom** [comment]
FWIW I played around with tooltips and never found a solution I loved. Some obstacles:

- npm modules that were big and drew in dependencies
- npm modules that didn't support HTML (for links)
- npm modules that did, but only as strings, and I, new to React, didn't know how to render the citation safely as a string
- (specifically, the citations all have links inside \<angle brackets\>, which need to be escaped)
- even if everything works, some of the citations are just a lot of text for a tooltip
