### ISSUE TITLE
Refactor data fetching

### ISSUE THREAD

**Issue by rosslh** [rosslh/IsEarthStillWarming.com#7]

**Comment by Aditya-Kolla** [comment]
Hello, do you have any ideas of how you want the data fetching to be refactored to?
I'm willing to work on this.

**Comment by Aditya-Kolla** [comment]
Alright, I'll look into it.

**Comment by rosslh** [comment]
Great! I already split up the getData function but please make a pull request if you think there are further improvements you can make
