### ISSUE TITLE
Fix build failure

### ISSUE THREAD

**Issue by rosslh** [rosslh/IsEarthStillWarming.com#95]
Looks like an issue with our scripps data source

**Comment by EmanuelGF** [comment]
Greetings.
On **static.config.js** changed the the axios call on the **getCo2** function to :  **`https://scrippsco2.ucsd.edu/assets/data/atmospheric/merged_ice_core_mlo_spo/merged_ice_core_yearly.csv`**.

**Comment by rosslh** [comment]
Took me long enough :)
